# Generated by Django 5.1.4 on 2024-12-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="role_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
