# Generated by Django 5.1.4 on 2024-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershiprequest",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
