# Generated by Django 5.1.4 on 2024-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("editor", "Editor "),
                ],
                max_length=10,
            ),
        ),
    ]
