# Generated by Django 5.1.4 on 2024-12-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admin_panel.userprofile",
            ),
        ),
    ]
