# Generated by Django 5.1.4 on 2024-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_article_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revision requested", "Revision Requested"),
                ],
                max_length=20,
            ),
        ),
    ]
