# Generated by Django 5.1.4 on 2024-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="moderator_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
