# Generated by Django 5.1.4 on 2024-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_membershiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="work_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
