# Generated by Django 5.1.4 on 2024-12-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_userprofile_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="role_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
