# Generated by Django 5.1.4 on 2024-12-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_article_role_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiprequest",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershiprequest",
            name="role_assigned",
            field=models.BooleanField(default=False),
        ),
    ]
