# Generated by Django 5.1.4 on 2024-12-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0013_membershiprequest_is_approved_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MembershipRequest",
        ),
    ]
