# Generated by Django 5.1.4 on 2024-12-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0015_membershiprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
