# Generated by Django 5.1.4 on 2024-12-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0016_article_published_article_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_articles",
                to="admin_panel.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_articles",
                to="admin_panel.category",
            ),
        ),
    ]
