# Generated by Django 5.1.4 on 2025-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_category_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_id',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
