# Generated by Django 5.1.4 on 2025-05-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_userprofile_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_id',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
