# Generated by Django 5.1.4 on 2024-12-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0017_alter_article_assigned_to_alter_article_category"),
        ("editor_panel", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editor_articles",
                to="admin_panel.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editor_articles",
                to="admin_panel.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="draft",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="admin_panel.article",
            ),
        ),
    ]
